---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: fare-docker-reg.dock.studios:5000/docker-images/cpp-static-code-analysis:latest
  secrets: [ARTIFACT_USERNAME, ARTIFACT_PASSWORD, ARTIFACT_BASE_URL]
  commands:
  - cmake .
  - make clean all
  - curl --fail -k -u "$ARTIFACT_USERNAME:$ARTIFACT_PASSWORD" --upload-file ./GameboyEmulator $ARTIFACT_BASE_URL/${DRONE_COMMIT}/GameboyEmulator

- name: System tests
  image: fare-docker-reg.dock.studios:5000/docker-images/screenshot-tool:latest
  commands:
  - bash ./tests/system/01-special.sh
  - bash ./tests/system/02-interrupts.sh
  - bash ./tests/system/03-op_sp,hl.sh
  - bash ./tests/system/04-op_r,imm.sh
  - bash ./tests/system/05-op_rp.sh
  - bash ./tests/system/06-ld_r,r.sh
  - bash ./tests/system/07-jr,jp,call,ret,rst.sh
  - bash ./tests/system/08-misc-instrs.sh
  - bash ./tests/system/09-op_r,r.sh
  - bash ./tests/system/10-bit_ops.sh
  - bash ./tests/system/11-op_a,-hl.sh


