---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: fare-docker-reg.dock.studios:5000/docker-images/cpp-static-code-analysis:latest
  commands:
  - cmake .
  - make clean all
  - curl -k -u "$ARTIFACT_USERNAME{}:${ARTIFACT_PASSWORD}" --upload-file ./GameboyEmulator ${ARTIFACT_BASE_URL}/${DRONE_COMMIT}/GameboyEmulator


